### ISSUE TITLE
bug with affix option

### ISSUE THREAD

**Issue by Saniok88** [imevul/ArkInventory_Attune#1]
When i enabled it in settings, then opened bags - got that error message.
In my case addon is unusable with that new affix option enabled.
Im not sure, if it just me, or if that report is informative, but i just leave it here:

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:5966: attempt to call field 'GetAttunedSuffix' (a nil value)
Time: 04/01/24 00:11:08
Count: 2
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:5966: in function `Frame_Item_Update_Attunement'
Interface\AddOns\ArkInventory\ArkInventory.lua:5650: in function `Frame_Item_Update_Texture'
Interface\AddOns\ArkInventory\ArkInventory.lua:5337: in function `Frame_Bar_DrawItems'
Interface\AddOns\ArkInventory\ArkInventory.lua:5036: in function `Frame_Container_Draw'
Interface\AddOns\ArkInventory\ArkInventory.lua:4200: in function `Frame_Main_Draw'
Interface\AddOns\ArkInventory\ArkInventory.lua:3562: in function `Frame_Main_DrawLocation'
Interface\AddOns\ArkInventory\ArkInventory.lua:3553: in function `Frame_Main_Generate'
Interface\AddOns\ArkInventory\ArkInventory.lua:4299: in function `Frame_Main_Show'
Interface\AddOns\ArkInventory\ArkInventory.lua:4264: in function `Frame_Main_Toggle'
Interface\AddOns\ArkInventory\ArkInventory.lua:7739: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:7732>
(tail call): ?
Interface\FrameXML\MainMenuBarBagButtons.lua:54: in function `BackpackButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals: frame = ARKINV_Frame1ContainerBag4Item12 {
 UpdateTooltip = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:6078
 count = 1
 0 = <userdata>
 ARK_Data = <table> {
 }
 hasItem = 1
 SplitStack = <function> defined @Interface\FrameXML\ContainerFrame.lua:617
}
framename = "ARKINV_Frame1ContainerBag4Item12"
obj_name = "ArkAttunementProgress"
obj = ARKINV_Frame1ContainerBag4Item12ArkAttunementProgress {
 0 = <userdata>
}
i = <table> {
 q = 3
 cat = "2!2"
 class = "item"
 bag_id = 4
 h = "[Defiler's Plate Greaves]"
 loc_id = 1
 count = 1
 sb = true
 slot_id = 12
 age = 28531894
 new = 1
}
enabled = true
colorBlindMode = true
showSuffix = true
progressWidth = 6
progressMinHeight = 6
progressMaxHeight = 35
itemId = 20208
_ = "Defiler's Plate Greaves"
_ = "[Defiler's Plate Greaves]"
itemQuality = 3
actualSuffixId = 0
(*temporary) = nil
(*temporary) = 20208
(*temporary) = "attempt to call field 'GetAttunedSuffix' (a nil value)"

**Comment by imevul** [comment]
I think what's happening is that you have an older version of SynastriaCoreLib that gets loaded, and the embedded version is ignored

**Comment by imevul** [comment]
I should probably start using LibStub to solve this, but in the mean time you can make sure you upgrade all addons and that any standalone or embedded corelib is version 1.0.4

**Comment by imevul** [comment]
Please try updating the addons now and see if you still have problems :)
