### ISSUE TITLE
attunableatall() not working due to typo in referenced lib function.

### ISSUE THREAD

**Issue by cfedey** [imevul/ArkInventory_Attune#2]
https://github.com/imevul/ArkInventory_Attune/blob/1818eeceb8fe1959edc69075b14ebde1c4df97ae/src/ArkInventoryRules_Attunables/ArkInventoryRules_Attunables.lua#L77

IsAttunablebySomeone should be IsAttunableBySomeone to match the function in Attunement.lua of SynastriaCoreLib.

**Comment by imevul** [comment]
Should be fixed in 1.0.10+
