### ISSUE TITLE
Expansion-based filters use the wrong ItemIDs.

### ISSUE THREAD

**Issue by cfedey** [imevul/ArkInventory_Attune#4]
https://github.com/imevul/ArkInventory_Attune/blob/b40163eaeed92d82179d863ff9108434a527890a/src/ArkInventoryRules_Misc/ArkInventoryRules_Misc.lua#L2-L5

I believe these itemIDs aren't correct. I did a little guess-and-checking on the server DB and it looks like the actual IDs should be:

Vanilla: 1
TBC: 23329
WotLK: 35570
Mythic: 52202

Feel free to double check with whatever source you prefer. I assumed that there was no overlap between the highest previous expansion item and the lowest next expansion item when I did my checking.

If you want a quick proof that the current ranges aren't right, check [Cataclysm's Edge](https://wowgaming.altervista.org/aowow/?item=30902). ItemID 30902 but it's a Mount Hyjal drop, so it's a TBC item.

**Comment by imevul** [comment]
Yeah, these are rough estimates since I didn't know of a sure way to find out the exact IDs. Do you have an example of a mythic item as low as 52202? All the IDs I've received from server admin was atleast 60k+

**Comment by cfedey** [comment]
No, I don't actually know where mythic items start.

All I did was stumble around the server DB plugging in itemIDs until i found the border between expansions. 52201 is the highest I could find for an obtainable WotLK item, so 52202 made sense to me for the start of mythics, since it's the end of non-custom items. Granted 52202 is a real item, albeit unavailable to players, so I guess 52203 is a better choice.

If meh said all mythics are 60000+ then that could be fine, but if he ever backfills the empty space between 52203 and 59999, things would get mis-sorted. Whereas knowing the highest possible WotLK item is 52202, it's more future-proof to set it to that instead of 60000.

**Comment by imevul** [comment]
True. That's sounds reasonable. He didn't actually confirm one way or the other, just that all IDs I've ever received were 60k+. I'll change it to 52203 for now.

**Comment by imevul** [comment]
Fixed in https://github.com/imevul/ArkInventory_Attune/releases/tag/1.0.12

**Comment by cfedey** [comment]
Hi, sorry to reopen this, but I was too conservative with my previous approach. The highest WotLK itemID is 56806, as seen here:

https://wowgaming.altervista.org/aowow/?items&filter=cr=151;crs=1;crv=52202#0-1-2

and here:
https://www.wowhead.com/wotlk/items?filter=151;1;52202#items;450-1+20 (scroll down past all of the new classic items. the next lowest itemID after Mini Thor is 92533, and obviously that's not an original WotLK item.)

Would've been a lot easier on me if I used that itemID filter the first time, but oh well. So with that, I propose the Mythic ID floor should be changed from 52203 to 56807.

**Comment by imevul** [comment]
Thanks. I'll update the range.

**Comment by imevul** [comment]
Fixed in https://github.com/imevul/ArkInventory_Attune/releases/tag/1.0.13
